# Generated by Django 3.0.5 on 2020-04-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100)),
                ('companyPerson', models.CharField(max_length=100)),
                ('companyTel', models.CharField(max_length=100)),
                ('companyEmail', models.EmailField(max_length=254)),
                ('companyComment', models.TextField()),
                ('isView', models.BooleanField(default=False)),
            ],
        ),
    ]
